server:
  port: 8001

spring:
  #  MySQL数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #MySQL配置
    driverClassName: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://localhost:3306/admissions?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://localhost:3306/admissions?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useUnicode=true&useSSL=true

    username: root
    password: 1234

  #时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  global-config:
    db-config:
      id-type: auto  # 鼠标放在id-type上面显示的解释如下图。
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
logging:
  level:
    com.qing.gulimall.product: error

